### ISSUE TITLE
Set default firewalld policy

### ISSUE THREAD

**Issue by greg-hellings** [oasis-roles/ansible_collection_system#27]
User should be able to set the default mode on the firewalld zone. Something like this:

```yaml
- name: firewalld | Checking firewalld target policy
  command: "/usr/bin/firewall-cmd --zone public --get-target --permanent"
  changed_when: firewalld_public_policy.stdout != 'DROP'
  register: firewalld_public_policy

- name: firewalld | Enforce drop policy on firewall public zone
  command: "/usr/bin/firewall-cmd --zone public --set-target DROP --permanent"
  when: firewalld_public_policy.stdout != 'DROP'
  notify:
    - firewalld_reload
```
